# Generated by Django 4.1.1 on 2022-09-14 13:20

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('prog 001', 'prog 001'), ('prog 002', 'prog 002'), ('prog 003', 'prog 003')], default='green', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('surface', models.FloatField()),
                ('prix', models.FloatField()),
                ('nbre_piece', models.IntegerField()),
                ('my_field2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('piscine', 'piscine'), ('jardin', 'jardin'), ('cave', 'cave'), ('parking', 'jardin'), ('proche station ski', 'proche station ski')], default=None, max_length=20, null=True)),
                ('prog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ImmoApp.program')),
            ],
        ),
    ]
