# Generated by Django 4.1.1 on 2022-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImmoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='dispo',
            field=models.BooleanField(default=True),
        ),
    ]
