# Generated by Django 4.1.1 on 2022-09-14 13:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ImmoApp', '0002_program_dispo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartement',
            name='my_field2',
        ),
        migrations.AddField(
            model_name='appartement',
            name='caract',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('piscine', 'piscine'), ('jardin', 'jardin'), ('cave', 'cave'), ('parking', 'jardin'), ('proche station ski', 'proche station ski')], default=None, max_length=20, null=True),
        ),
    ]
